# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of PioneerBPA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Append the derived cohorts into the base cohort table
#'
#' Copies the derived cohorts (\code{90100}-\code{90224}) from
#' \code{cohortTableNew} into the base \code{cohortTable}, so that the target
#' cohorts and the outcome cohorts (\code{1775}-\code{1813}, generated by
#' \code{\link{generateStudyCohorts}}) live in a single table. This is required
#' by \code{\link{runIRandTTEAnalysis}}, whose SQL joins the target and outcome
#' cohorts inside one \code{@cohort_table}.
#'
#' For the appended rows, \code{cohort_end_date} is set to the \strong{end of
#' continuous observation} - the \code{observation_period_end_date} of the
#' observation period that contains \code{cohort_start_date} - so that
#' follow-up for these targets runs to the end of available observation. Note
#' this differs from the same cohorts in \code{cohortTableNew}, which retain the
#' metastasis cohort end date used by \code{\link{runDerivedCohortDiagnostics}}.
#'
#' Subjects whose \code{cohort_start_date} is not covered by an observation
#' period are dropped (\code{INNER JOIN}), consistent with the incidence-rate /
#' time-to-event SQL, which also requires observation at cohort entry. The
#' operation is idempotent: rows for the derived \code{cohort_definition_id}
#' values are deleted from \code{cohortTable} before insertion, so re-runs do
#' not duplicate rows.
#'
#' @param connectionDetails    DatabaseConnector connection details object.
#'   Ignored when \code{connection} is supplied.
#' @param connection           An optional open DatabaseConnector connection.
#'   When \code{NULL} a connection is opened from \code{connectionDetails} and
#'   disconnected on exit.
#' @param cdmDatabaseSchema    Schema containing the OMOP CDM tables
#'   (\code{observation_period}).
#' @param cohortDatabaseSchema Schema holding the cohort tables.
#' @param cohortTable          Base cohort table that holds the outcome cohorts
#'   and into which the derived target cohorts are appended.
#' @param cohortTableNew       Derived cohort table holding the \code{90xxx}
#'   cohorts.
#' @param packageName          Name of the package holding the SQL resources.
#'
#' @export
appendDerivedCohortsToBase <- function(connectionDetails = NULL,
                                       connection = NULL,
                                       cdmDatabaseSchema,
                                       cohortDatabaseSchema,
                                       cohortTable,
                                       cohortTableNew,
                                       packageName = "PioneerBPA") {

  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }

  ParallelLogger::logInfo(
    "Appending derived cohorts from ", cohortTableNew, " into ", cohortTable,
    " (cohort_end_date = end of continuous observation)"
  )

  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename            = "appendDerivedToCohortTable.sql",
    packageName            = packageName,
    dbms                   = connection@dbms,
    cohort_database_schema = cohortDatabaseSchema,
    cdm_database_schema    = cdmDatabaseSchema,
    cohort_table           = cohortTable,
    cohortTableNew         = cohortTableNew
  )
  DatabaseConnector::executeSql(connection, sql)

  invisible(NULL)
}
